# Generated by Django 4.2.3 on 2023-07-27 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="status",
            field=models.CharField(
                choices=[("Done", "Done"), ("Not done", "Not done")], max_length=60
            ),
        ),
    ]
